services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoist
    ports:
      - "${TODO_PORT:-7540}:${TODO_PORT:-7540}"
    environment:
      - TODO_PORT=${TODO_PORT:-7540}
      - TODO_DBFILE=${TODO_DBFILE:-scheduler.db}
      - TODO_PASSWORD=${TODO_PASSWORD:-12345}
    volumes:
      - ./scheduler.db:/app/scheduler.db
    restart: unless-stopped